.TH gitta 1 "" "gitta 0.1.0" "User Commands"
.SH NAME
gitta \- placeholder Python CLI
.SH SYNOPSIS
.B gitta
[
.I options
]
.SH DESCRIPTION
Minimal CLI that prints help and a hello subcommand.
.SH OPTIONS
.TP
.B \-V, \-\-version
Show version.
.SH SEE ALSO
Project homepage: https://gegge01.github.io/gitta

