name: nightly

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch: {}

jobs:
  build-deb:
    name: Nightly .deb (amd64)
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Build wheel
        run: |
          python -m pip install --upgrade build
          python -m build
        - name: NFPM Packaging
          uses: nfpm/nfpm-action@v2
        with:
          install-only: true
      - name: Import GPG and export public key
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          set -e
          echo "$GPG_PRIVATE_KEY" | gpg --batch --passphrase "$GPG_PASSPHRASE" --pinentry-mode loopback --import
          KEY_FPR=$(gpg --list-secret-keys --with-colons | awk -F: '/^sec/{print $5;exit}')
          echo "Using key: $KEY_FPR"
          mkdir -p build/gpg
          gpg --armor --export "$KEY_FPR" > build/gpg/pubkey.asc
      - name: Compute nightly version
        id: ver
        run: |
          DATE=$(date -u +%Y%m%d)
          SHA=$(git rev-parse --short=8 HEAD)
          VERSION="0.1.0-nightly.${DATE}+${SHA}"
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
      - name: Build deb via nfpm (nightly)
        env:
          VERSION: ${{ steps.ver.outputs.version }}
        run: |
          set -e
          echo "Using version: $VERSION"
          sed -i -E "s/^version: .*/version: ${VERSION}/" nfpm.yaml
          mkdir -p dist
          nfpm pkg --packager deb -f nfpm.yaml --target dist/gitta_${VERSION}_amd64.deb
      - name: Build archive-keyring deb (nightly)
        env:
          VERSION: ${{ steps.ver.outputs.version }}
        run: |
          set -e
          sed -i -E "s/^version: .*/version: ${VERSION}/" nfpm.keyring.yaml
          nfpm pkg --packager deb -f nfpm.keyring.yaml --target dist/gitta-archive-keyring_${VERSION}_all.deb
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nightly-debs
          path: dist/*.deb

  publish-apt:
    name: Publish APT nightly to GitHub Pages
    runs-on: ubuntu-latest
    needs: smoke-test
    permissions:
      contents: write
    steps:
      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages
      - name: Download nightly artifacts
        uses: actions/download-artifact@v4
        with:
          name: nightly-debs
          path: gh-pages
      - name: Install apt tools
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y -qq apt-utils gnupg
      - name: Import GPG key
        working-directory: gh-pages
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          set -e
          echo "$GPG_PRIVATE_KEY" | gpg --batch --passphrase "$GPG_PASSPHRASE" --pinentry-mode loopback --import
          KEY_FPR=$(gpg --list-secret-keys --with-colons | awk -F: '/^sec/{print $5;exit}')
          echo "$KEY_FPR:6:" | gpg --import-ownertrust
          echo "Using key $KEY_FPR"
      - name: Export public key
        working-directory: gh-pages
        run: |
          KEY_FPR=$(gpg --list-secret-keys --with-colons | awk -F: '/^sec/{print $5;exit}')
          gpg --armor --export "$KEY_FPR" > pubkey.asc
      - name: Publish APT metadata (nightly)
        working-directory: gh-pages
        env:
          PACKAGE_NAME: gitta
          ARCHES: amd64
          DEB_GLOB: "*.deb"
          DIST: nightly
        run: |
          bash ../build/publish-apt.sh
      - name: Commit and push
        working-directory: gh-pages
        run: |
          set -e
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add -A
          git commit -m "Nightly APT update $(date -u +%F)" || echo "No changes"
          git push origin HEAD:gh-pages

  smoke-test:
    name: Smoke test .deb in container
    runs-on: ubuntu-latest
    permissions:
      actions: read
    needs: build-deb
    steps:
      - uses: actions/checkout@v4
      - name: Download nightly artifacts
        uses: actions/download-artifact@v4
        with:
          name: nightly-debs
          path: dist
      - name: List artifacts
        run: ls -la dist
      - name: Run smoke test
        run: |
          chmod +x scripts/smoke-test.sh
          DEB=$(ls dist/*.deb | head -n1)
          echo "Testing $DEB"
          bash scripts/smoke-test.sh "$DEB"
