name: nightly

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch: {}

jobs:
  build-deb:
    name: Nightly .deb (amd64)
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Build wheel
        run: |
          python -m pip install --upgrade build
          python -m build
      - name: Install nfpm (standalone binary)
        env:
          NFPM_VERSION: 2.38.1
        run: |
          set -e
          ARCH=$(dpkg --print-architecture)
          case "$ARCH" in
            amd64) NFPM_ARCH="x86_64" ;;
            arm64) NFPM_ARCH="arm64" ;;
            armhf) NFPM_ARCH="armv7" ;;
            *) echo "Unsupported arch: $ARCH"; exit 1 ;;
          esac
          URL="https://github.com/goreleaser/nfpm/releases/download/v${NFPM_VERSION}/nfpm_Linux_${NFPM_ARCH}.tar.gz"
          echo "Downloading $URL"
          curl -fsSL -o /tmp/nfpm.tgz "$URL"
          mkdir -p /tmp/nfpm
          tar -xzf /tmp/nfpm.tgz -C /tmp/nfpm
          if [ -f /tmp/nfpm/nfpm ]; then
            sudo install -m 0755 /tmp/nfpm/nfpm /usr/local/bin/nfpm
          else
            sudo install -m 0755 /tmp/nfpm/*/nfpm /usr/local/bin/nfpm
          fi
          nfpm --version
      - name: Import GPG and export public key
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          set -e
          echo "$GPG_PRIVATE_KEY" | gpg --batch --passphrase "$GPG_PASSPHRASE" --pinentry-mode loopback --import
          KEY_FPR=$(gpg --list-secret-keys --with-colons | awk -F: '/^sec/{print $5;exit}')
          echo "Using key: $KEY_FPR"
          mkdir -p build/gpg
          gpg --armor --export "$KEY_FPR" > build/gpg/pubkey.asc
      - name: Compute nightly version
        id: ver
        run: |
          DATE=$(date -u +%Y%m%d)
          SHA=$(git rev-parse --short=8 HEAD)
          VERSION="0.1.0-nightly.${DATE}+${SHA}"
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
      - name: Build deb via nfpm (nightly; amd64, arm64)
        env:
          VERSION: ${{ steps.ver.outputs.version }}
        run: |
          set -e
          echo "Using version: $VERSION"
          sed -i -E "s/^version: .*/version: ${VERSION}/" nfpm.yaml
          mkdir -p dist
          for ARCH in amd64 arm64; do
            sed -i -E "s/^arch: .*/arch: ${ARCH}/" nfpm.yaml
            nfpm pkg --packager deb -f nfpm.yaml --target dist/gitta_${VERSION}_${ARCH}.deb
          done
      - name: Build archive-keyring deb (nightly)
        env:
          VERSION: ${{ steps.ver.outputs.version }}
        run: |
          set -e
          sed -i -E "s/^version: .*/version: ${VERSION}/" nfpm.keyring.yaml
          nfpm pkg --packager deb -f nfpm.keyring.yaml --target dist/gitta-archive-keyring_${VERSION}_all.deb
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nightly-debs
          path: dist/*.deb

  publish-apt:
    name: Publish APT nightly to Cloudflare R2
    runs-on: ubuntu-latest
    needs: smoke-test
    permissions:
      contents: read
    steps:
      - name: Download nightly artifacts
        uses: actions/download-artifact@v4
        with:
          name: nightly-debs
          path: repo
      - name: Install apt tools and awscli
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y -qq apt-utils gnupg awscli
      - name: Import GPG key
        working-directory: repo
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          set -e
          echo "$GPG_PRIVATE_KEY" | gpg --batch --passphrase "$GPG_PASSPHRASE" --pinentry-mode loopback --import
          KEY_FPR=$(gpg --list-secret-keys --with-colons | awk -F: '/^sec/{print $5;exit}')
          echo "$KEY_FPR:6:" | gpg --import-ownertrust
          echo "Using key $KEY_FPR"
      - name: Export public key
        working-directory: repo
        run: |
          KEY_FPR=$(gpg --list-secret-keys --with-colons | awk -F: '/^sec/{print $5;exit}')
          gpg --armor --export "$KEY_FPR" > pubkey.asc
      - name: Publish APT metadata (nightly)
        working-directory: repo
        env:
          PACKAGE_NAME: gitta
          ARCHES: amd64,arm64
          DEB_GLOB: "*.deb"
          DIST: nightly
        run: |
          bash ../build/publish-apt.sh
      - name: Sync nightly to Cloudflare R2
        working-directory: repo
        env:
          # Credentials must remain secrets
          AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          # Non-sensitive config via repo/org variables
          R2_BUCKET: ${{ vars.R2_BUCKET }}
          R2_PREFIX: ${{ vars.R2_PREFIX }}
          R2_ENDPOINT: ${{ vars.R2_ENDPOINT }}
          # Optional fallback if endpoint not set
          R2_ACCOUNT_ID: ${{ vars.R2_ACCOUNT_ID }}
        run: |
          set -e
          PREFIX_PATH="${R2_PREFIX:+/${R2_PREFIX}}"
          if [ -n "${R2_ENDPOINT:-}" ]; then
            ENDPOINT="$R2_ENDPOINT"
          elif [ -n "${R2_ACCOUNT_ID:-}" ]; then
            ENDPOINT="https://${R2_ACCOUNT_ID}.r2.cloudflarestorage.com"
          else
            echo "Missing R2 endpoint configuration: set R2_ENDPOINT or R2_ACCOUNT_ID as GitHub variables." >&2
            exit 1
          fi
          aws s3 sync . "s3://${R2_BUCKET}${PREFIX_PATH}" --endpoint-url "$ENDPOINT" --delete --only-show-errors
      - name: Set Cache-Control on APT metadata (nightly)
        working-directory: repo
        env:
          R2_BUCKET: ${{ vars.R2_BUCKET }}
          R2_PREFIX: ${{ vars.R2_PREFIX }}
          R2_ENDPOINT: ${{ vars.R2_ENDPOINT }}
          R2_ACCOUNT_ID: ${{ vars.R2_ACCOUNT_ID }}
        run: |
          set -e
          PREFIX_PATH="${R2_PREFIX:+/${R2_PREFIX}}"
          if [ -n "${R2_ENDPOINT:-}" ]; then
            ENDPOINT="$R2_ENDPOINT"
          elif [ -n "${R2_ACCOUNT_ID:-}" ]; then
            ENDPOINT="https://${R2_ACCOUNT_ID}.r2.cloudflarestorage.com"
          else
            echo "Missing R2 endpoint configuration: set R2_ENDPOINT or R2_ACCOUNT_ID as GitHub variables." >&2
            exit 1
          fi
          aws s3 cp "s3://${R2_BUCKET}${PREFIX_PATH}/dists" "s3://${R2_BUCKET}${PREFIX_PATH}/dists" \
            --recursive --exclude "*" \
            --include "*/InRelease" --include "*/Release" --include "*/Release.gpg" --include "*/Packages" \
            --endpoint-url "$ENDPOINT" --metadata-directive REPLACE --cache-control "no-cache" --content-type "text/plain" --only-show-errors || true
          aws s3 cp "s3://${R2_BUCKET}${PREFIX_PATH}/dists" "s3://${R2_BUCKET}${PREFIX_PATH}/dists" \
            --recursive --exclude "*" --include "*/Packages.gz" \
            --endpoint-url "$ENDPOINT" --metadata-directive REPLACE --cache-control "no-cache" --content-type "application/gzip" --only-show-errors || true

  smoke-test:
    name: Smoke test .deb in container
    runs-on: ubuntu-latest
    permissions:
      actions: read
    needs: build-deb
    steps:
      - uses: actions/checkout@v4
      - name: Download nightly artifacts
        uses: actions/download-artifact@v4
        with:
          name: nightly-debs
          path: dist
      - name: List artifacts
        run: ls -la dist
      - name: Run smoke test
        run: |
          chmod +x scripts/smoke-test.sh
          DEB=$(ls dist/*.deb | head -n1)
          echo "Testing $DEB"
          bash scripts/smoke-test.sh "$DEB"
