name: release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch: {}

jobs:
  build-deb:
    name: Build .deb (amd64)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Build wheel
        run: |
          python -m pip install --upgrade build
          python -m build
      - name: Install nfpm (standalone binary)
        env:
          NFPM_VERSION: 2.38.1
        run: |
          set -e
          ARCH=$(dpkg --print-architecture)
          case "$ARCH" in
            amd64) NFPM_ARCH="x86_64" ;;
            arm64) NFPM_ARCH="arm64" ;;
            armhf) NFPM_ARCH="armv7" ;;
            *) echo "Unsupported arch: $ARCH"; exit 1 ;;
          esac
          URL="https://github.com/goreleaser/nfpm/releases/download/v${NFPM_VERSION}/nfpm_Linux_${NFPM_ARCH}.tar.gz"
          echo "Downloading $URL"
          curl -fsSL -o /tmp/nfpm.tgz "$URL"
          mkdir -p /tmp/nfpm
          tar -xzf /tmp/nfpm.tgz -C /tmp/nfpm
          # Install binary, whether it's at root or inside a folder
          if [ -f /tmp/nfpm/nfpm ]; then
            sudo install -m 0755 /tmp/nfpm/nfpm /usr/local/bin/nfpm
          else
            sudo install -m 0755 /tmp/nfpm/*/nfpm /usr/local/bin/nfpm
          fi
          nfpm --version
      - name: Import GPG and export public key
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          set -e
          echo "$GPG_PRIVATE_KEY" | gpg --batch --passphrase "$GPG_PASSPHRASE" --pinentry-mode loopback --import
          KEY_FPR=$(gpg --list-secret-keys --with-colons | awk -F: '/^sec/{print $5;exit}')
          echo "Using key: $KEY_FPR"
          mkdir -p build/gpg
          gpg --armor --export "$KEY_FPR" > build/gpg/pubkey.asc
      - name: Build deb via nfpm
        env:
          VERSION: ${{ github.ref_name && startsWith(github.ref_name, 'v') && github.ref_name != '' && format('{0}', github.ref_name) || '' }}
        run: |
          set -e
          VERSION="${GITHUB_REF_NAME#v}"
          echo "Using version: $VERSION"
          sed -i -E "s/^version: .*/version: ${VERSION}/" nfpm.yaml
          mkdir -p dist
          nfpm pkg --packager deb -f nfpm.yaml --target dist/gitta_${VERSION}_amd64.deb
      - name: Build archive-keyring deb
        env:
          VERSION: ${{ github.ref_name && startsWith(github.ref_name, 'v') && github.ref_name != '' && format('{0}', github.ref_name) || '' }}
        run: |
          set -e
          VERSION="${GITHUB_REF_NAME#v}"
          sed -i -E "s/^version: .*/version: ${VERSION}/" nfpm.keyring.yaml
          nfpm pkg --packager deb -f nfpm.keyring.yaml --target dist/gitta-archive-keyring_${VERSION}_all.deb
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: debs
          path: dist/*.deb

  publish-apt:
    name: Publish APT repo to Cloudflare R2
    runs-on: ubuntu-latest
    needs: smoke-test
    permissions:
      contents: read
    steps:
      - name: Download deb artifacts
        uses: actions/download-artifact@v4
        with:
          name: debs
          path: repo
      - name: Install apt tools and awscli
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y -qq apt-utils gnupg awscli
      - name: Import GPG key
        working-directory: repo
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          set -e
          echo "$GPG_PRIVATE_KEY" | gpg --batch --passphrase "$GPG_PASSPHRASE" --pinentry-mode loopback --import
          KEY_FPR=$(gpg --list-secret-keys --with-colons | awk -F: '/^sec/{print $5;exit}')
          echo "$KEY_FPR:6:" | gpg --import-ownertrust
          echo "Using key $KEY_FPR"
      - name: Export public key
        working-directory: repo
        run: |
          KEY_FPR=$(gpg --list-secret-keys --with-colons | awk -F: '/^sec/{print $5;exit}')
          gpg --armor --export "$KEY_FPR" > pubkey.asc
      - name: Publish APT metadata (InRelease + Release.gpg)
        working-directory: repo
        env:
          PACKAGE_NAME: gitta
          ARCHES: amd64
          DEB_GLOB: "*.deb"
        run: |
          bash ../build/publish-apt.sh
      - name: Sync to Cloudflare R2
        working-directory: repo
        env:
          # Credentials must remain secrets
          AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          # Non-sensitive config via repo/org variables
          R2_BUCKET: ${{ vars.R2_BUCKET }}
          R2_PREFIX: ${{ vars.R2_PREFIX }}
          R2_ENDPOINT: ${{ vars.R2_ENDPOINT }}
          # Optional fallback if endpoint not set
          R2_ACCOUNT_ID: ${{ vars.R2_ACCOUNT_ID }}
        run: |
          set -e
          PREFIX_PATH="${R2_PREFIX:+/${R2_PREFIX}}"
          if [ -n "${R2_ENDPOINT:-}" ]; then
            ENDPOINT="$R2_ENDPOINT"
          elif [ -n "${R2_ACCOUNT_ID:-}" ]; then
            ENDPOINT="https://${R2_ACCOUNT_ID}.r2.cloudflarestorage.com"
          else
            echo "Missing R2 endpoint configuration: set R2_ENDPOINT or R2_ACCOUNT_ID as GitHub variables." >&2
            exit 1
          fi
          aws s3 sync . "s3://${R2_BUCKET}${PREFIX_PATH}" --endpoint-url "$ENDPOINT" --delete --only-show-errors

  smoke-test:
    name: Smoke test .deb in container
    runs-on: ubuntu-latest
    permissions:
      contents: read
    needs: build-deb
    steps:
      - uses: actions/checkout@v4
      - name: Download deb artifacts
        uses: actions/download-artifact@v4
        with:
          name: debs
          path: dist
      - name: List artifacts
        run: ls -la dist
      - name: Run smoke test
        run: |
          chmod +x scripts/smoke-test.sh
          DEB=$(ls dist/*.deb | head -n1)
          echo "Testing $DEB"
          bash scripts/smoke-test.sh "$DEB"
